[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
target = "web"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3
startPeriod = "40s"

[[services]]
name = "devops-notes-web" 