name: Deploy to Cloud

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-staging:
    if: github.event.inputs.environment == 'staging' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging server
        run: |
          echo "Deploying to staging environment..."
          # Example: Deploy to your staging server
          # ssh user@staging-server "cd /app && docker compose pull && docker compose up -d"
          
          # Or deploy to cloud platforms:
          # - AWS ECS
          # - Google Cloud Run
          # - Azure Container Instances
          # - DigitalOcean App Platform
          # - Railway
          # - Render
          # - Fly.io
          
          echo "Staging deployment completed!"

  deploy-production:
    if: github.event.inputs.environment == 'production' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production server
        run: |
          echo "Deploying to production environment..."
          # Example: Deploy to your production server
          # ssh user@prod-server "cd /app && docker compose pull && docker compose up -d"
          
          # Or deploy to cloud platforms:
          # - AWS ECS
          # - Google Cloud Run
          # - Azure Container Instances
          # - DigitalOcean App Platform
          # - Railway
          # - Render
          # - Fly.io
          
          echo "Production deployment completed!" 